version: '3.3'

services:
  mongodb:
    image: mongo:7.0.7
    restart: always
    ports:
      - 27017:27017
    networks:
      - myjobapplicationsnetwork

  app:
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - myjobapplicationsnetwork


networks:
  myjobapplicationsnetwork: {}